/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekpbo.views;

import javax.swing.JLabel;
import projekpbo.controllers.GameController;

/**
 *
 * @author Lenovo
 */
public class PlayerView extends javax.swing.JFrame {

    /**
     * Creates new form PlayerView
     */
    
    private GameController controller;
    public PlayerView() {
        initComponents();
        controller = new GameController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelJudulPlayer = new javax.swing.JLabel();
        jLabelKata = new javax.swing.JLabel();
        jLabelTebak = new javax.swing.JLabel();
        jTextFieldTebak = new javax.swing.JTextField();
        jButtonTebak = new javax.swing.JButton();
        jLabelHurufBetul = new javax.swing.JLabel();
        jLabelKesalahan = new javax.swing.JLabel();
        jButtonMuat = new javax.swing.JButton();
        jButtonKeluar = new javax.swing.JButton();
        jLabelKata2 = new javax.swing.JLabel();
        jLabelTebakan = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelhuruf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelJudulPlayer.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabelJudulPlayer.setForeground(new java.awt.Color(255, 153, 0));
        jLabelJudulPlayer.setText("wordhunter");

        jLabelKata.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabelKata.setText("Kata:");

        jLabelTebak.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabelTebak.setText("Tebakan");

        jTextFieldTebak.setBackground(new java.awt.Color(255, 204, 51));
        jTextFieldTebak.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jTextFieldTebak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTebakActionPerformed(evt);
            }
        });

        jButtonTebak.setBackground(new java.awt.Color(255, 153, 0));
        jButtonTebak.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jButtonTebak.setText("Tebak");
        jButtonTebak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTebakActionPerformed(evt);
            }
        });

        jLabelHurufBetul.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabelHurufBetul.setText("Huruf Ditebak:  ");

        jLabelKesalahan.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabelKesalahan.setText("Kesempatan: ");

        jButtonMuat.setBackground(new java.awt.Color(255, 153, 0));
        jButtonMuat.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jButtonMuat.setText("Muat Ulang");
        jButtonMuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMuatActionPerformed(evt);
            }
        });

        jButtonKeluar.setBackground(new java.awt.Color(255, 153, 0));
        jButtonKeluar.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jButtonKeluar.setText("Keluar");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekpbo/WhatsApp_Image_2025-05-10_at_18.00.58_fd20e6a3__1_-removebg-preview.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabelhuruf.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabelJudulPlayer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelKesalahan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotal)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelTebakan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelHurufBetul)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelhuruf)
                                        .addGap(348, 348, 348)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonTebak, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelKata)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                                .addComponent(jLabelKata2)
                                                .addGap(446, 446, 446))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelTebak)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldTebak))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(412, 412, 412)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButtonKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonMuat, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 36, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelJudulPlayer)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotal)
                    .addComponent(jLabelKesalahan))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelKata)
                    .addComponent(jLabelKata2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTebak, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTebak))
                .addGap(18, 18, 18)
                .addComponent(jButtonTebak, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabelTebakan)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonMuat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHurufBetul)
                            .addComponent(jLabel1)
                            .addComponent(jLabelhuruf))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTebakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTebakActionPerformed
        String input =jTextFieldTebak.getText().trim().toUpperCase();
        if(!input.isEmpty()){
            controller.prosesTebak(input);
            jTextFieldTebak.setText("");
        }
    }//GEN-LAST:event_jButtonTebakActionPerformed

    private void jButtonMuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMuatActionPerformed
        controller.muatUlang();
    }//GEN-LAST:event_jButtonMuatActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jTextFieldTebakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTebakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTebakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerView().setVisible(true);
            }
        });
    }

    public JLabel getjLabelKata2() {
        return jLabelKata2;
    }

    public JLabel getjLabelTebakan() {
        return jLabelhuruf;
    }

    public JLabel getjLabelTotal() {
        return jLabelTotal;
    }
    
    public void setKataTerbuka(String kata) {
        jLabelKata2.setText(kata);
    }

    public void setHurufTebakan(String huruf) {
        jLabelhuruf.setText(huruf);
       }

    public void setJumlahKesalahan(int jumlah) {
        jLabelTotal.setText(String.valueOf(jumlah));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonMuat;
    private javax.swing.JButton jButtonTebak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelHurufBetul;
    private javax.swing.JLabel jLabelJudulPlayer;
    private javax.swing.JLabel jLabelKata;
    private javax.swing.JLabel jLabelKata2;
    private javax.swing.JLabel jLabelKesalahan;
    private javax.swing.JLabel jLabelTebak;
    private javax.swing.JLabel jLabelTebakan;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelhuruf;
    private javax.swing.JTextField jTextFieldTebak;
    // End of variables declaration//GEN-END:variables
}
